apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vuoe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vuoe
    app.kubernetes.io/part-of: ci10t-777-0072-app
  name: devfile-sample-vuoe
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vuoe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vuoe
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-777-0072-tenant/ci10t-777-0072-app/devfile-sample-vuoe@sha256:e9e3c676e140a4d34b9e467a890e069224d87f0ff21e7a950cb990cf931f03d2
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
